/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx,md}",
    "./lib/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      pri: "var(--col-pri)",
      priTxt: "var(--col-on-pri)",
      sec: "var(--col-sec)",
      secTxt: "var(--col-on-sec)",
      ok: "var(--col-ok)",
      okTxt: "var(--col-on-ok)",
      err: "var(--col-err)",
      errTxt: "var(--col-on-err)",
      warn: "var(--col-warn)",
      warnTxt: "var(--col-on-warn)",
      info: "var(--col-info)",
      infoTxt: "var(--col-on-info)",
      txt0: "var(--col-txt-0)",
      txt1: "var(--col-txt-1)",
      txt2: "var(--col-txt-2)",
      txt3: "var(--col-txt-3)",
      txt4: "var(--col-txt-4)",
      txt5: "var(--col-txt-5)",
      txt6: "var(--col-txt-6)",
      bg0: "var(--col-bg-0)",
      bg1: "var(--col-bg-1)",
      bg2: "var(--col-bg-2)",
      bg3: "var(--col-bg-3)",
      bg4: "var(--col-bg-4)",
      bg5: "var(--col-bg-5)",
      bg6: "var(--col-bg-6)",
      black: "black",
      white: "white",
      transparent: "transparent",
    },
  },
  plugins: [],
};
