/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/components/': RouteRecordInfo<'/components/', '/components', Record<never, never>, Record<never, never>>,
    '/components/button': RouteRecordInfo<'/components/button', '/components/button', Record<never, never>, Record<never, never>>,
    '/components/chartPie': RouteRecordInfo<'/components/chartPie', '/components/chartPie', Record<never, never>, Record<never, never>>,
    '/components/dataGrid': RouteRecordInfo<'/components/dataGrid', '/components/dataGrid', Record<never, never>, Record<never, never>>,
    '/components/dateTimePicker': RouteRecordInfo<'/components/dateTimePicker', '/components/dateTimePicker', Record<never, never>, Record<never, never>>,
    '/components/dateTimePicker_native': RouteRecordInfo<'/components/dateTimePicker_native', '/components/dateTimePicker_native', Record<never, never>, Record<never, never>>,
    '/components/dialog': RouteRecordInfo<'/components/dialog', '/components/dialog', Record<never, never>, Record<never, never>>,
    '/components/dialog_service': RouteRecordInfo<'/components/dialog_service', '/components/dialog_service', Record<never, never>, Record<never, never>>,
    '/components/dragDrop': RouteRecordInfo<'/components/dragDrop', '/components/dragDrop', Record<never, never>, Record<never, never>>,
    '/components/form': RouteRecordInfo<'/components/form', '/components/form', Record<never, never>, Record<never, never>>,
    '/components/iconClass': RouteRecordInfo<'/components/iconClass', '/components/iconClass', Record<never, never>, Record<never, never>>,
    '/components/input': RouteRecordInfo<'/components/input', '/components/input', Record<never, never>, Record<never, never>>,
    '/components/popover': RouteRecordInfo<'/components/popover', '/components/popover', Record<never, never>, Record<never, never>>,
    '/components/progressBar': RouteRecordInfo<'/components/progressBar', '/components/progressBar', Record<never, never>, Record<never, never>>,
    '/components/range': RouteRecordInfo<'/components/range', '/components/range', Record<never, never>, Record<never, never>>,
    '/components/select': RouteRecordInfo<'/components/select', '/components/select', Record<never, never>, Record<never, never>>,
    '/components/select_box': RouteRecordInfo<'/components/select_box', '/components/select_box', Record<never, never>, Record<never, never>>,
    '/components/switch': RouteRecordInfo<'/components/switch', '/components/switch', Record<never, never>, Record<never, never>>,
    '/components/tabs': RouteRecordInfo<'/components/tabs', '/components/tabs', Record<never, never>, Record<never, never>>,
    '/components/textarea': RouteRecordInfo<'/components/textarea', '/components/textarea', Record<never, never>, Record<never, never>>,
    '/components/timePicker': RouteRecordInfo<'/components/timePicker', '/components/timePicker', Record<never, never>, Record<never, never>>,
    '/components/virtualScroll': RouteRecordInfo<'/components/virtualScroll', '/components/virtualScroll', Record<never, never>, Record<never, never>>,
    '/introduction/': RouteRecordInfo<'/introduction/', '/introduction', Record<never, never>, Record<never, never>>,
    '/introduction/main.css': RouteRecordInfo<'/introduction/main.css', '/introduction/main/css', Record<never, never>, Record<never, never>>,
    '/introduction/main.ts': RouteRecordInfo<'/introduction/main.ts', '/introduction/main/ts', Record<never, never>, Record<never, never>>,
    '/introduction/packageJson': RouteRecordInfo<'/introduction/packageJson', '/introduction/packageJson', Record<never, never>, Record<never, never>>,
    '/introduction/style': RouteRecordInfo<'/introduction/style', '/introduction/style', Record<never, never>, Record<never, never>>,
    '/introduction/tsconfig': RouteRecordInfo<'/introduction/tsconfig', '/introduction/tsconfig', Record<never, never>, Record<never, never>>,
    '/introduction/viteConfig': RouteRecordInfo<'/introduction/viteConfig', '/introduction/viteConfig', Record<never, never>, Record<never, never>>,
    '/sandbox/': RouteRecordInfo<'/sandbox/', '/sandbox', Record<never, never>, Record<never, never>>,
    '/sandbox/chartGantt': RouteRecordInfo<'/sandbox/chartGantt', '/sandbox/chartGantt', Record<never, never>, Record<never, never>>,
    '/sandbox/colors': RouteRecordInfo<'/sandbox/colors', '/sandbox/colors', Record<never, never>, Record<never, never>>,
    '/sandbox/datagrid': RouteRecordInfo<'/sandbox/datagrid', '/sandbox/datagrid', Record<never, never>, Record<never, never>>,
    '/sandbox/DatagridServ': RouteRecordInfo<'/sandbox/DatagridServ', '/sandbox/DatagridServ', Record<never, never>, Record<never, never>>,
    '/sandbox/DatagridServer': RouteRecordInfo<'/sandbox/DatagridServer', '/sandbox/DatagridServer', Record<never, never>, Record<never, never>>,
    '/sandbox/dragDrop': RouteRecordInfo<'/sandbox/dragDrop', '/sandbox/dragDrop', Record<never, never>, Record<never, never>>,
    '/sandbox/gantt': RouteRecordInfo<'/sandbox/gantt', '/sandbox/gantt', Record<never, never>, Record<never, never>>,
    '/sandbox/testForms': RouteRecordInfo<'/sandbox/testForms', '/sandbox/testForms', Record<never, never>, Record<never, never>>,
    '/sandbox/virScroll': RouteRecordInfo<'/sandbox/virScroll', '/sandbox/virScroll', Record<never, never>, Record<never, never>>,
    '/styles/': RouteRecordInfo<'/styles/', '/styles', Record<never, never>, Record<never, never>>,
    '/styles/Background_Text': RouteRecordInfo<'/styles/Background_Text', '/styles/Background_Text', Record<never, never>, Record<never, never>>,
    '/styles/Brand_colors': RouteRecordInfo<'/styles/Brand_colors', '/styles/Brand_colors', Record<never, never>, Record<never, never>>,
  }
}
