module.exports = {
  ".col-pri": {
    "background-color": "var(--col-pri)",
    color: "var(--col-on-pri)",
    "--current-bg-col": "var(--col-pri)",
    "--current-txt-col": "var(--col-on-pri)",
  },
  ".col-sec": {
    "background-color": "var(--col-sec)",
    color: "var(--col-on-sec)",
    "--current-bg-col": "var(--col-sec)",
    "--current-txt-col": "var(--col-on-sec)",
  },
  ".col-ok": {
    "background-color": "var(--col-ok)",
    color: "var(--col-on-ok)",
    "--current-bg-col": "var(--col-ok)",
    "--current-txt-col": "var(--col-on-ok)",
  },
  ".col-err": {
    "background-color": "var(--col-err)",
    color: "var(--col-on-err)",
    "--current-bg-col": "var(--col-err)",
    "--current-txt-col": "var(--col-on-err)",
  },
  ".col-warn": {
    "background-color": "var(--col-warn)",
    color: "var(--col-on-warn)",
    "--current-bg-col": "var(--col-warn)",
    "--current-txt-col": "var(--col-on-warn)",
  },
  ".col-info": {
    "background-color": "var(--col-info)",
    color: "var(--col-on-info)",
    "--current-bg-col": "var(--col-info)",
    "--current-txt-col": "var(--col-on-info)",
  },
  ".col-black": {
    "background-color": "black",
    color: "white",
    "--current-bg-col": "black",
    "--current-txt-col": "white",
  },
  ".col-white": {
    "background-color": "white",
    color: "black",
    "--current-bg-col": "white",
    "--current-txt-col": "black",
  },
  ".iconBtn": {
    "border-radius": "50%",
    "background-color": "transparent",
    color: "var(--current-bg-col);",
  },
  ".iconBtn-outline": {
    "background-color": "transparent",
    color: "var(--current-bg-col);",
    border: "solid 1px currentColor",
    "border-radius": "4px",
    padding: "2px",
  },
  ".iconBtn-outline-round": {
    "border-radius": "50%",
    "background-color": "transparent",
    color: "var(--current-bg-col);",
    border: "solid 1px currentColor",
    padding: "2px",
  },
  ".iconBtn-filled": {
    "background-color": "var(--current-bg-col)",
    color: "var(--current-txt-col)",
    "border-radius": "4px",
    padding: "3px",
  },
  ".iconBtn-filled-round": {
    "border-radius": "50%",
    "background-color": "var(--current-bg-col)",
    color: "var(--current-txt-col)",
    padding: "3px",
  },
};
