/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");

const hhlTailwind = plugin(
  function ({ addComponents, theme }) {
    addComponents({
      ":root": {
        "--col-pri": "#6594c5",
        "--col-on-pri": "#fff",
        "--col-sec": "#6c757d",
        "--col-on-sec": "#fff",
        "--col-ok": "#28a745",
        "--col-on-ok": "#fff",
        "--col-err": "#dc3545",
        "--col-on-err": "#fff",
        "--col-warn": "#ffc107",
        "--col-on-warn": "black",
        "--col-info": "#17a2b8",
        "--col-on-info": "#fff",
        "--col-txt-0": "hsl(0, 0%, 0%)",
        "--col-txt-1": "hsl(0, 0%, 17%)",
        "--col-txt-2": "hsl(0, 0%, 27%)",
        "--col-txt-3": "hsl(0, 0%, 37%)",
        "--col-txt-4": "hsl(0, 0%, 47%)",
        "--col-txt-5": "hsl(0, 0%, 57%)",
        "--col-txt-6": "hsl(0, 0%, 67%)",
        "--col-bg-drawer": "#f3f3f3",
        "--col-bg-0": "hsl(0, 0%, 100%)",
        "--col-bg-1": "hsl(0, 0%, 95%)",
        "--col-bg-2": "hsl(0, 0%, 92%)",
        "--col-bg-3": "hsl(0, 0%, 88%)",
        "--col-bg-4": "hsl(0, 0%, 84%)",
        "--col-bg-5": "hsl(0, 0%, 80%)",
        "--col-bg-6": "hsl(0, 0%, 76%)",
        color: "var(--col-txt-0)",
      },
      ".darkTheme": {
        "--col-txt-0": "rgb(255, 255, 255)",
        "--col-txt-1": "rgba(255, 255, 255, 0.87)",
        "--col-txt-2": "rgba(255, 255, 255, 0.6)",
        "--col-txt-3": "rgba(255, 255, 255, 0.45)",
        "--col-txt-4": "rgba(255, 255, 255, 0.3)",
        "--col-txt-5": "rgba(255, 255, 255, 0.2)",
        "--col-txt-6": "rgba(255, 255, 255, 0.1)",
        "--col-bg-drawer": "#1f1f1f",
        "--col-bg-0": "hsl(231, 12%, 20%)",
        "--col-bg-1": "hsl(231, 12%, 23%)",
        "--col-bg-2": "hsl(231, 12%, 27%)",
        "--col-bg-3": "hsl(231, 12%, 32%)",
        "--col-bg-4": "hsl(231, 12%, 35%)",
        "--col-bg-5": "hsl(231, 12%, 39%)",
        "--col-bg-6": "hsl(231, 12%, 43%)",
        "color-scheme": "dark",
        color: "var(--col-txt-0)",
      },
      ".col-pri": {
        "background-color": "var(--col-pri)",
        color: "var(--col-on-pri)",
        "--current-bg-col": "var(--col-pri)",
        "--current-txt-col": "var(--col-on-pri)",
      },
      ".col-sec": {
        "background-color": "var(--col-sec)",
        color: "var(--col-on-sec)",
        "--current-bg-col": "var(--col-sec)",
        "--current-txt-col": "var(--col-on-sec)",
      },
      ".col-ok": {
        "background-color": "var(--col-ok)",
        color: "var(--col-on-ok)",
        "--current-bg-col": "var(--col-ok)",
        "--current-txt-col": "var(--col-on-ok)",
      },
      ".col-err": {
        "background-color": "var(--col-err)",
        color: "var(--col-on-err)",
        "--current-bg-col": "var(--col-err)",
        "--current-txt-col": "var(--col-on-err)",
      },
      ".col-warn": {
        "background-color": "var(--col-warn)",
        color: "var(--col-on-warn)",
        "--current-bg-col": "var(--col-warn)",
        "--current-txt-col": "var(--col-on-warn)",
      },
      ".col-info": {
        "background-color": "var(--col-info)",
        color: "var(--col-on-info)",
        "--current-bg-col": "var(--col-info)",
        "--current-txt-col": "var(--col-on-info)",
      },
      ".col-black": {
        "background-color": "black",
        color: "white",
        "--current-bg-col": "black",
        "--current-txt-col": "white",
      },
      ".col-white": {
        "background-color": "white",
        color: "black",
        "--current-bg-col": "white",
        "--current-txt-col": "black",
      },
    });
  },
  {
    theme: {
      colors: {
        pri: "var(--col-pri)",
        priTxt: "var(--col-on-pri)",
        sec: "var(--col-sec)",
        secTxt: "var(--col-on-sec)",
        ok: "var(--col-ok)",
        okTxt: "var(--col-on-ok)",
        err: "var(--col-err)",
        errTxt: "var(--col-on-err)",
        warn: "var(--col-warn)",
        warnTxt: "var(--col-on-warn)",
        info: "var(--col-info)",
        infoTxt: "var(--col-on-info)",
        txt0: "var(--col-txt-0)",
        txt1: "var(--col-txt-1)",
        txt2: "var(--col-txt-2)",
        txt3: "var(--col-txt-3)",
        txt4: "var(--col-txt-4)",
        txt5: "var(--col-txt-5)",
        txt6: "var(--col-txt-6)",
        bg0: "var(--col-bg-0)",
        bg1: "var(--col-bg-1)",
        bg2: "var(--col-bg-2)",
        bg3: "var(--col-bg-3)",
        bg4: "var(--col-bg-4)",
        bg5: "var(--col-bg-5)",
        bg6: "var(--col-bg-6)",
        black: "black",
        white: "white",
        transparent: "transparent",
        current: "currentColor",
      },
    },
  }
);

module.exports = hhlTailwind;
