const C = require("./Colors");
module.exports = {
  ":root": {
    "--col-pri": C.pri,
    "--col-on-pri": C.priTxt,
    "--col-sec": C.sec,
    "--col-on-sec": C.secTxt,
    "--col-ok": C.ok,
    "--col-on-ok": C.okTxt,
    "--col-err": C.err,
    "--col-on-err": C.errTxt,
    "--col-warn": C.warn,
    "--col-on-warn": C.warnTxt,
    "--col-info": C.info,
    "--col-on-info": C.infoTxt,
    "--col-txt-0": C.txt0,
    "--col-txt-1": C.txt1,
    "--col-txt-2": C.txt2,
    "--col-txt-3": C.txt3,
    "--col-txt-4": C.txt4,
    "--col-txt-5": C.txt5,
    "--col-txt-6": C.txt6,
    "--col-bg-drawer": C.drawer,
    "--col-bg-0": C.bg0,
    "--col-bg-1": C.bg1,
    "--col-bg-2": C.bg2,
    "--col-bg-3": C.bg3,
    "--col-bg-4": C.bg4,
    "--col-bg-5": C.bg5,
    "--col-bg-6": C.bg6,
    color: "var(--col-txt-0)",
  },
  ".darkTheme": {
    "--col-txt-0": C.dark.txt0,
    "--col-txt-1": C.dark.txt1,
    "--col-txt-2": C.dark.txt2,
    "--col-txt-3": C.dark.txt3,
    "--col-txt-4": C.dark.txt4,
    "--col-txt-5": C.dark.txt5,
    "--col-txt-6": C.dark.txt6,
    "--col-bg-drawer": C.dark.drawer,
    "--col-bg-0": C.dark.bg0,
    "--col-bg-1": C.dark.bg1,
    "--col-bg-2": C.dark.bg2,
    "--col-bg-3": C.dark.bg3,
    "--col-bg-4": C.dark.bg4,
    "--col-bg-5": C.dark.bg5,
    "--col-bg-6": C.dark.bg6,
    "color-scheme": "dark",
  },
  "div[class*='ico-']::after": {
    content: "''",
    "-webkit-mask": "var(--svg) no-repeat",
    mask: "var(--svg) no-repeat",
    "-webkit-mask-size": "100% 100%",
    "mask-size": "100% 100%",
    "background-color": "currentColor",
    color: "inherit",
    width: "1.4em",
    height: "1.4em",
    display: "block",
  },
  "div[class*='iconBtn']": {
    display: "inline-flex",
    height: "1.4em",
    "align-items": "center",
    width: "1.4em",
    "&:hover": {
      outline: "2px solid var(--col-pri)",
    },
    "&:active": {
      outline: "2px solid var(--col-pri)",
      transform: "scale(0.9)",
    },
    "&[disabled]": {
      opacity: ".35",
      "pointer-events": "none",
    },
  },
  "div[class*='iconBtn-filled']": {
    "--current-txt-col": "var(--col-txt-2)",
    "--current-bg-col": "var(--col-bg-3)",
  },
  ":fullscreen": {
    "background-color": "var(--col-bg-0)",
  },
};
