import C from "./Colors";
module.exports = {
  pri: `var(--col-pri,${C.pri})`,
  priTxt: `var(--col-on-pri,${C.priTxt})`,
  sec: `var(--col-sec,${C.sec})`,
  secTxt: `var(--col-on-sec,${C.secTxt})`,
  ok: `var(--col-ok,${C.ok})`,
  okTxt: `var(--col-on-ok,${C.okTxt})`,
  err: `var(--col-err,${C.err})`,
  errTxt: `var(--col-on-err,${C.errTxt})`,
  warn: `var(--col-warn,${C.warn})`,
  warnTxt: `var(--col-on-warn,${C.warnTxt})`,
  info: `var(--col-info,${C.info})`,
  infoTxt: `var(--col-on-info,${C.infoTxt})`,
  txt0: `var(--col-txt-0,${C.txt0})`,
  txt1: `var(--col-txt-1,${C.txt1})`,
  txt2: `var(--col-txt-2,${C.txt2})`,
  txt3: `var(--col-txt-3,${C.txt3})`,
  txt4: `var(--col-txt-4,${C.txt4})`,
  txt5: `var(--col-txt-5,${C.txt5})`,
  txt6: `var(--col-txt-6,${C.txt6})`,
  bg0: `var(--col-bg-0,${C.bg0})`,
  bg1: `var(--col-bg-1,${C.bg1})`,
  bg2: `var(--col-bg-2,${C.bg2})`,
  bg3: `var(--col-bg-3,${C.bg3})`,
  bg4: `var(--col-bg-4,${C.bg4})`,
  bg5: `var(--col-bg-5,${C.bg5})`,
  bg6: `var(--col-bg-6,${C.bg6})`,
  black: "black",
  white: "white",
  transparent: "transparent",
  current: "currentColor",
  currentBg: "var(--current-bg-col)",
};
